config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/contact", to: "static_pages#contact"
    get "/search", to: "static_pages#search"
    post "/add_cart", to: "carts#add_to_cart"
    get "/cart", to: "carts#show"
    delete "/cart", to: "carts#destroy"
    patch "/cart", to: "carts#update"

    namespace :admin do
      resources :users
      resources :categories
      resources :products
      resources :orders, only: %i(index edit update)
      resources :order_details, only: :show
    end
    resources :orders, except: %i(edit update show)
    resources :users, only: %i(new create edit update)
    resources :products, only: %i(show index)
    resources :categories, only: %i(show index)
    devise_for :users, :path => "", :path_names => {:sign_in => "login", :sign_out => "logout", :edit => "profile", :confirmation => "confirmations"}, skip: :omniauth_callbacks
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy
  has_many :products, through: :order_details
  enum status: {waiting: 0, delivering: 1, delivered: 2, cancel: 3}
  validates :name_order, presence: true
  validates :address_order, presence: true
  validates :phone_order, presence: true
  scope :new_order, ->{order(created_at: :DESC)}
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  layout "application_admin"
  before_action :load_orders, only: %i(edit update)

  def index
    @search = Order.search params[:q]
    @orders = @search.result.new_order.paginate page: params[:page],
      per_page: Settings.admin.product_limit
    @search.build_condition
  end

  def edit; end

  def update
    if @order.update_attribute :status, params[:order][:status]
      send_mails @order
      flash[:success] = t "admin.update_success"
      redirect_to admin_orders_path
    else
      flash[:danger] = t "admin.update_fail"
      render :edit
    end
  end

  private

  def load_orders
    @order = Order.find_by id: params[:id]
    return if @order
    flash[:danger] = "Order invalid"
    redirect_to orders_path
  end

  def order_params
    params.require(:order).permit :name_order, :address_order,
      :phone_order, :total_amount, :status
  end

  def send_mails order
    OrderMailer.update_order(order).deliver
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  authorize_resource
  before_action :load_orders, only: :destroy

  def index
    @orders = current_user.orders.new_order.paginate page: params[:page],
      per_page: Settings.history_order
  end

  def new
    @order = Order.new
    @carts =  load_cart_session
    @products = Product.find_multi_ids @carts.keys
    @sum_total = load_sum_total @carts, @products
  end

  def create
    @carts = load_cart_session
    return unless @carts
    Order.transaction do
      @order = current_user.orders.build order_param
      @order.save
      update_order_detail @carts, @order
      decrease_number_product @order, @carts
      send_mails current_user, @order, @carts
      remove_all_cart
      flash[:success] = t "checkout.success"
      redirect_to root_path
    end
    rescue
      flash[:danger] = t "checkout.not_success"
      render :new
  end

  def destroy
    Order.transaction do
      @order.update_attribute :status, Settings.order.cancle
      increase_number_product @order
      flash[:success] = t "order.order_cancle"
      redirect_to orders_path
    end
    rescue
      flash[:danger] = t "order.order_cancle_error"
      render :index
  end

  private

  def load_orders
    @order = Order.find_by id: params[:id]
    return if @order
    flash[:danger] = t "order.invalid"
    redirect_to orders_path
  end

  def decrease_number_product order, cart
    order.products.each do |product|
      number = product.quantity - cart[product.id.to_s]
      product.update_attribute :quantity, number
    end
  end

  def increase_number_product order
    order.order_details.each do |order_detail|
      product_quantity = get_product(order_detail).quantity
      number = product_quantity + order_detail.quantity
      product = get_product order_detail
      product.update_attribute :quantity, number
    end
  end

  def order_param
    params.require(:order).permit :name_order, :phone_order,
      :address_order, :total_amount
  end

  def update_order_detail carts, order
    carts.each do |product_id, quantity|
      order.order_details.create! product_id: product_id, quantity: quantity
    end
  end

  def send_mails user, order, carts
    OrderMailer.order_email(user, order, carts).deliver
  end
end

app/views/admin/orders/_form.html.erb
<%= form_for [:admin, @order] do |f| %>
  <%= f.label :name_order, t("sessions.new.name") %>
  <%= f.text_field :name_order, class: "form-control" %>

  <%= f.label :address_order, t("mailer.quantity") %>
  <%= f.text_field :address_order, class: "form-control" %>

  <%= f.label :phone_order, t("mailer.quantity") %>
  <%= f.text_field :phone_order, class: "form-control" %>

  <%= f.label :total_amount, t("mailer.quantity") %>
  <%= f.number_field :total_amount, class: "form-control" %>


  <%= f.label :status, t("mailer.status") %>
  <%= f.select(:status, load_order_status, {include_blank: true}, class: "form-control") %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/orders/_order.html.erb
<tr>
  <td><%= order.name_order %></td>
  <td><%= order.address_order %></td>
  <td><%= order.phone_order %></td>
  <td><%= t("product_price", price: order.total_amount) %></td>
  <td><%= order.status %></td>
  <td><%= order.user.email %></td>
  <td><%= link_to t("order.update"), edit_admin_order_path(order), class: "btn btn-success" %></td>
  <td><%= link_to t("order.view_detail"), admin_order_detail_path(order), class: "btn btn-success" %></td>
</tr>

app/views/admin/orders/edit.html.erb
<h1><%= t "order.edit" %></h1>

<%= form_for [:admin, @order] do |f| %>
  <%= render "shared/error_messages", object: @order %>
  <%= f.label :status, t("mailer.status") %>
  <%= f.select(:status, load_order_status, {include_blank: true}, class: "form-control") %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Orders</h1>

<%= search_form_for [:admin, @search] do |f| %>
  <%= f.condition_fields do |c| %>
    <div>
      <%= c.attribute_fields do |a| %>
        <%= a.attribute_select%>
      <% end %>
    <%= c.predicate_select %>
    <%= c.value_fields do |v| %>
      <%= v.text_field :value %>
    <% end %>
    </div>
  <% end %>

  <%= f.submit "Search", class: "btn btn-primary" %>
<% end %>

<%= will_paginate %>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t "order.name" %></th>
      <th><%= t "order.address" %></th>
      <th><%= t "order.phone" %></th>
      <th><%= t "order.total" %> </th>
      <th><%= t "order.status" %></th>
      <th><%= t "order.email" %></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "order", collection: @orders, as: "order" %>
  </tbody>
</table>