config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/contact", to: "static_pages#contact"
    get "/search", to: "static_pages#search"
    post "/add_cart", to: "carts#add_to_cart"
    get "/cart", to: "carts#show"
    delete "/cart", to: "carts#destroy"
    patch "/cart", to: "carts#update"

    namespace :admin do
      resources :users
      resources :categories
      resources :products
      resources :orders, only: %i(index edit update)
      resources :order_details, only: :show
    end
    resources :orders, except: %i(edit update show)
    resources :users, only: %i(new create edit update)
    resources :products, only: %i(show index)
    resources :categories, only: %i(show index)
    devise_for :users, :path => "", :path_names => {:sign_in => "login", :sign_out => "logout", :edit => "profile", :confirmation => "confirmations"}, skip: :omniauth_callbacks
  end
end

app/views/shared/_aside_menu.html.erb
<ul class="aside-menu">
  <% @categories.each do |category| %>
    <li><%= link_to category.name_category, category %></li>
  <% end %>
</ul>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t(".messages", count: object.errors.size) %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer" class="color-div">
    <div class="container">
      <div class="row">
        <div class="col-sm-3">
          <div class="widget">
            <h4 class="widget-title">Instagram Feed</h4>
            <div id="beta-instagram-feed"><div></div></div>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="widget">
            <h4 class="widget-title">Information</h4>
            <div>
              <ul>
                <li><a href="blog_fullwidth_2col.html"><i class="fa fa-chevron-right"></i> Web Design</a></li>
                <li><a href="blog_fullwidth_2col.html"><i class="fa fa-chevron-right"></i> Web development</a></li>
                <li><a href="blog_fullwidth_2col.html"><i class="fa fa-chevron-right"></i> Marketing</a></li>
                <li><a href="blog_fullwidth_2col.html"><i class="fa fa-chevron-right"></i> Tips</a></li>
                <li><a href="blog_fullwidth_2col.html"><i class="fa fa-chevron-right"></i> Resources</a></li>
                <li><a href="blog_fullwidth_2col.html"><i class="fa fa-chevron-right"></i> Illustrations</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
         <div class="col-sm-10">
          <div class="widget">
            <h4 class="widget-title">Contact Us</h4>
            <div>
              <div class="contact-info">
                <i class="fa fa-map-marker"></i>
                <p>30 South Park Avenue San Francisco, CA 94108 Phone: +78 123 456 78</p>
                <p>Nemo enim ipsam voluptatem quia voluptas sit asnatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione.</p>
              </div>
            </div>
          </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="widget">
            <h4 class="widget-title">Newsletter Subscribe</h4>
            <form action="#" method="post">
              <input type="email" name="your_email">
              <button class="pull-right" type="submit">Subscribe <i class="fa fa-chevron-right"></i></button>
            </form>
          </div>
        </div>
      </div> <!-- .row -->
    </div> <!-- .container -->
</div> <!-- #footer -->
<div class="copyright">
  <div class="container">
    <p class="pull-left">Privacy policy. (&copy;) 2014</p>
    <p class="pull-right pay-options">
      <a href="#"><img src="assets/dest/images/pay/master.jpg" alt="" /></a>
      <a href="#"><img src="assets/dest/images/pay/pay.jpg" alt="" /></a>
      <a href="#"><img src="assets/dest/images/pay/visa.jpg" alt="" /></a>
      <a href="#"><img src="assets/dest/images/pay/paypal.jpg" alt="" /></a>
    </p>
    <div class="clearfix"></div>
  </div> <!-- .container -->
</div> <!-- .copyright -->

app/views/shared/_header.html.erb
<div id="header">
  <div class="header-top">
    <div class="container">
      <div class="pull-left auto-width-left">
        <ul class="top-menu menu-beta l-inline">
          <li><a href=""><i class="fa fa-home"></i> 640 Trung Nu Vuong, Da Nang City</a></li>
          <li><a href=""><i class="fa fa-phone"></i> 0961 141 478</a></li>
        </ul>
      </div>
      <div class="pull-right auto-width-right">
        <ul class="top-details menu-beta l-inline">
          <% if !user_signed_in? %>
            <li><%= link_to t(".login"), new_user_session_path %></li>
            <li><%= link_to t(".signup"), new_user_registration_path %></li>
          <% else %>
            <li><%= link_to t(".logout"), destroy_user_session_path, method: :delete %></li>
            <li> <%= link_to orders_path do  %>
              <i class="fa fa-user"></i><%= t ".history" %>
            </li>
            <% end %>
            <li><%= link_to t(".change_password"), edit_user_registration_path %>
            </li>
            <% if can? :index, current_user %>
              <li>
                <%= link_to t(".admin_page"), admin_users_path %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
      <div class="clearfix"></div>
    </div> <!-- .container -->
  </div> <!-- .header-top -->
  <div class="header-body">
      <div class="container beta-relative">
        <div class="pull-left">
          <%= link_to root_path do %>
            <%= image_tag "logo.png", size: "200x100" %>
          <% end %>
        </div>
        <div class="pull-right beta-components space-left ov">
          <div class="space10">&nbsp;</div>
          <%= form_tag search_path, method: :GET do %>
            <div class="beta-comp">
                <div style="display: block;">
                  <%= text_field_tag :p %>
                </div>
            </div>
            <div class="beta-comp">
              <div>
                <%= button_tag :submit, class: "btn btn-secondary btn-number" do %>
                      <i class="fa fa-search"></i>
                    <% end %>
              </div> <!-- .cart -->
            </div>
          <% end %>
          <div class="beta-comp">
            <div class="cart">
              <%= link_to cart_path do %>
                <i class="fa fa-shopping-cart"></i> Cart (<%= load_size_cart %>) <i class="fa fa-chevron-down"></i>
              <% end %>
            </div> <!-- .cart -->
          </div>
        </div>
        <div class="clearfix"></div>
      </div> <!-- .container -->
  </div> <!-- .header-body -->
  <div class="header-bottom" style="background-color: #0277b8;">
      <div class="container">
        <a class="visible-xs beta-menu-toggle pull-right" href="#"><span class='beta-menu-toggle-text'>Menu</span> <i class="fa fa-bars"></i></a>
        <div class="visible-xs clearfix"></div>
        <nav class="main-menu">
          <ul class="l-inline ov">
            <li><%= link_to t(".home"), home_path %></li>
            <li><%= link_to t(".category"), categories_path %></li>
            <li><%= link_to t(".help"), help_path %></li>
            <li><%= link_to t(".contact"), contact_path %></li>
          </ul>
          <div class="clearfix"></div>
        </nav>
      </div> <!-- .container -->
  </div> <!-- .header-bottom -->
</div> <!-- #header -->

app/views/shared/_product_details.html.erb
<div class="col-sm-4">
  <div class="single-item">
    <div class="single-item-header">
      <%= link_to  product do %>
        <%= image_tag (get_image product), size: Settings.size_image %>
      <% end %>
    </div>
    <div class="single-item-body">
      <p class="single-item-title"><%= product.name %></p>
      <p class="single-item-price">
        <span><%= t("product_price", price:product.price) %></span>
      </p>
    </div>
    <div class="single-item-caption">
      <%= form_for :carts, url: add_cart_path, method: :POST do |f| %>
        <div><%= f.hidden_field :product_id, value: product.id %></div>

        <%= f.button :submit do %>
         <span class="add-to-cart pull-left" >
          <i class="fa fa-shopping-cart"></i>
          </span>
          <span class="beta-btn primary"> <%= t "add_cart" %> <i class="fa fa-chevron-right"></i> </span>
        <% end %>
      <% end %>
      <div class="clearfix"></div>
    </div>
  </div>
</div>

app/views/shared/_product_recentlys.html.erb
<div class="row">
  <% @load_product_recentlys.each do |product| %>
    <div class="col-sm-3">
      <div class="single-item">
        <div class="single-item-header">
          <%= link_to product do %>
            <%= image_tag (get_image product), size: Settings.size_image %>
          <% end %>
        </div>
        <div class="single-item-body">
          <p class="single-item-title"><%= product.name %></p>
          <p class="single-item-price">
            <span><%= t("product_price", price:product.price) %></span>
          </p>
        </div>
        <div class="single-item-caption">
          <%= form_for :carts, url: add_cart_path, method: :POST do |f| %>
            <div><%= f.hidden_field :product_id, value: product.id %></div>

            <%= f.button :submit do %>
             <span class="add-to-cart pull-left" >
              <i class="fa fa-shopping-cart"></i>
              </span>
              <span class="beta-btn primary" id="addcart"> Add to cart <i class="fa fa-chevron-right"></i> </span>
            <% end %>
          <% end %>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_slider.html.erb
<div class="rev-slider">
  <div class="fullwidthbanner-container">
    <div class="fullwidthbanner">
      <div class="bannercontainer" >
        <div class="banner" >
          <ul>
            <!-- THE FIRST SLIDE -->
            <li data-transition="boxfade" data-slotamount="20" class="active-revslide" style="width: 100%; height: 100%; overflow: hidden; z-index: 18; visibility: hidden; opacity: 0;">
                <div class="slotholder" style="width:100%;height:100%;" data-duration="undefined" data-zoomstart="undefined" data-zoomend="undefined" data-rotationstart="undefined" data-rotationend="undefined" data-ease="undefined" data-bgpositionend="undefined" data-bgposition="undefined" data-kenburns="undefined" data-easeme="undefined" data-bgfit="undefined" data-bgfitend="undefined" data-owidth="undefined" data-oheight="undefined">
                  <div class="tp-bgimg defaultimg" data-lazyload="undefined" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat" data-lazydone="undefined" src="assets/1.jpg" data-src="assets/1.jpg" style="background-color: rgba(0, 0, 0, 0); background-repeat: no-repeat; background-image: url('assets/1.jpg'); background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit;">
                  </div>
                </div>
            </li>
            <li data-transition="boxfade" data-slotamount="20" class="active-revslide" style="width: 100%; height: 100%; overflow: hidden; z-index: 18; visibility: hidden; opacity: 0;">
              <div class="slotholder" style="width:100%;height:100%;" data-duration="undefined" data-zoomstart="undefined" data-zoomend="undefined" data-rotationstart="undefined" data-rotationend="undefined" data-ease="undefined" data-bgpositionend="undefined" data-bgposition="undefined" data-kenburns="undefined" data-easeme="undefined" data-bgfit="undefined" data-bgfitend="undefined" data-owidth="undefined" data-oheight="undefined">
                <div class="tp-bgimg defaultimg" data-lazyload="undefined" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat" data-lazydone="undefined" src="assets/2.jpg" data-src="assets/2.jpg" style="background-color: rgba(0, 0, 0, 0); background-repeat: no-repeat; background-image: url('assets/2.jpg'); background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit;">
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="tp-bannertimer"></div>
    </div>
  </div>
</div>
 <!--slider end-->