config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/contact", to: "static_pages#contact"
    get "/search", to: "static_pages#search"
    post "/add_cart", to: "carts#add_to_cart"
    get "/cart", to: "carts#show"
    delete "/cart", to: "carts#destroy"
    patch "/cart", to: "carts#update"

    namespace :admin do
      resources :users
      resources :categories
      resources :products
      resources :orders, only: %i(index edit update)
      resources :order_details, only: :show
    end
    resources :orders, except: %i(edit update show)
    resources :users, only: %i(new create edit update)
    resources :products, only: %i(show index)
    resources :categories, only: %i(show index)
    devise_for :users, :path => "", :path_names => {:sign_in => "login", :sign_out => "logout", :edit => "profile", :confirmation => "confirmations"}, skip: :omniauth_callbacks
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name_category, presence: true,
    length: {minimum: Settings.category.length_minimum}
  validates :description, presence: true,
    length: {minimum: Settings.description.length_minimum}
  scope :sort_by_name, ->{order :name_category}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  layout "application_admin"
  before_action :load_admin_categories, except: %i(new index create)

  def index
    @categories = Category.paginate page: params[:page],
      per_page: Settings.categories_admin
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "admin.create_success"
      redirect_to admin_categories_path
    else
      flash[:danger] = t "admin.create_fail"
      render :new
    end
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "admin.update_success"
      redirect_to admin_categories_path
    else
      flash[:danger] = t "admin.update_fail"
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t "admin.delete_success"
    else
      flash[:danger] = t "admin.delete_fail"
    end
    redirect_to admin_categories_path
  end

  private

  def load_admin_categories
    @category = Category.find params[:id]
    return if @category
    flash[:danger] = t "category.not_found"
    redirect_to admin_categories_path
  end

  def category_params
    params.require(:category).permit :name_category, :description
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_categories, only: %i(index show)

  def index
    @products = Product.order(:name).paginate page: params[:page],
      per_page: Settings.paginate_view_home
  end

  def show
    @category = Category.find_by id: params[:id]
    return unless @category
    @list_products_by_category = @category.products
  end

  private

  def load_categories
    @categories = Category.sort_by_name
  end
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name_category, t("sessions.new.name") %>
  <%= f.text_field :name_category, class: "form-control" %>

  <%= f.label :description, t("category.description") %>
  <%= f.text_area(:description, size: Settings.size_text_area) %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing Admin Category</h1>

<%= render "form", category: @category %>

<%= link_to t("back_key"), admin_categories_path %>

app/views/admin/categories/index.html.erb
<h1>Admin Categories</h1>

<table class="table table-hover">
  <head>
    <tr>
      <th><%= t "category.id" %></th>
      <th><%= t "category.name" %></th>
      <th><%= t"category.description" %></th>
    <tr>
  <thead>

  <tbody>
    <%= will_paginate %>
    <% @categories.each do |admin_category| %>
      <tr>
        <td><%= admin_category.id %></td>
        <td><%= admin_category.name_category %></td>
        <td><%= admin_category.description %></td>>
        <td><%= link_to t("admin.edit"), edit_admin_category_path(admin_category), class: "btn btn-success" %></td>
        <td><%= link_to t("admin.destroy"), admin_category_path(admin_category), method: :delete, data: {confirm: t("admin.confirm_delete")}, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Admin Category", new_admin_category_path %>

app/views/admin/categories/new.html.erb
<h1>New Admin Category</h1>

<%= render "form", admin_category: @admin_category %>

<%= link_to t("back_key"), admin_categories_path %>