config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/contact", to: "static_pages#contact"
    get "/search", to: "static_pages#search"
    post "/add_cart", to: "carts#add_to_cart"
    get "/cart", to: "carts#show"
    delete "/cart", to: "carts#destroy"
    patch "/cart", to: "carts#update"

    namespace :admin do
      resources :users
      resources :categories
      resources :products
      resources :orders, only: %i(index edit update)
      resources :order_details, only: :show
    end
    resources :orders, except: %i(edit update show)
    resources :users, only: %i(new create edit update)
    resources :products, only: %i(show index)
    resources :categories, only: %i(show index)
    devise_for :users, :path => "", :path_names => {:sign_in => "login", :sign_out => "logout", :edit => "profile", :confirmation => "confirmations"}, skip: :omniauth_callbacks
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details
  enum status: {normal: 0, deleted: 1}
  delegate :name_category, to: :category
  accepts_nested_attributes_for :images, allow_destroy: true,
    reject_if: proc{|attributes| attributes["url_path"].blank?}
  scope :recently_view_product, (lambda do
    order(viewer: :DESC).limit(Settings.limit_product)
  end)
  scope :find_multi_ids, ->(ids){where id: ids}
  scope :product_active, ->{where status: 0}
  scope :new_product, ->{order(created_at: :DESC)}
  scope :search_by_name, ->(search_text){where "name LIKE ?", "%#{search_text}%" if search_text.present?}

  validates :name_category, presence: true,
    length: {maximum: Settings.length_name_maximum}
  validates :description, presence: true
  validates :quantity, presence: true
  validates :price, presence: true
  validates :status, presence: true
  validates :category_id, presence: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  layout "application_admin"
  before_action :load_admin_products, only: [:show, :edit, :update, :destroy]

  def index
    @search = Product.search params[:q]
    @products = @search.result.product_active.paginate page: params[:page],
      per_page: Settings.admin.product_limit
  end

  def new
    @product = Product.new
    @image = @product.images.build
  end

  def edit; end

  def create
    Product.transaction do
      @product = Product.new admin_product_params
      @product.save
      params[:images]["url_path"].each do |a|
        @image = @product.images.create!(url_path: a)
      end
    end
    flash[:success] = t "admin.update_success"
    redirect_to admin_products_path
  rescue StandardError
    flash[:danger] = t "admin.update_fail"
    render :edit
  end

  def update
    Product.transaction do
      @product.update_attributes admin_product_params
      params[:images]["url_path"].each do |a|
        @image = @product.images.create!(url_path: a)
      end
    end
    flash[:success] = t "admin.update_success"
    redirect_to admin_products_path
  rescue StandardError
    flash[:danger] = t "admin.update_fail"
    render :edit
  end

  def destroy
    if @product.update_attribute :status, :deleted
      flash[:danger] = t "admin.delete_success"
    else
      flash[:danger] = t "admin.delete_fail"
    end
    redirect_to admin_products_path
  end

  private

  def load_admin_products
    @product = Product.find params[:id]
    return if @product
    flash[:danger] = t "product.invalid"
    redirect_to admin_products_path
  end

  def admin_product_params
    params.require(:product).permit(:name, :description, :quantity,
      :price, :status, :category_id,
      images_attributes: [:id, :url_path])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, only: :show

  def show
    @product_news = Product.new_product.product_active
      .limit Settings.admin.product_limit
  end

  private

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product
    flash[:danger] = t "product.product_invalid"
    redirect_to root_path
  end
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product] do |f| %>
  <%= f.label :name, t("sessions.new.name") %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :description, t("category.description") %>
  <%= f.text_area(:description, size: Settings.size_text_area) %>

  <%= f.label :quantity, t("mailer.quantity") %>
  <%= f.number_field :quantity, class: "form-control" %>

  <%= f.label :price, t("mailer.price")  %>
  <%= f.number_field :price, class: "form-control" %>

  <%= f.label :status, t("mailer.status") %>
  <%= f.select(:status, load_status_option, {include_blank: true}, class: "form-control") %>

  <%= f.label :category, "Category" %>
  <%= f.select(:category_id, load_categories_option, {include_blank: false}, class: "form-control") %>
  <br>
  <%= f.fields_for :images do |p| %>
    <div class="field">
      <%= p.label :url_path %><br>
      <%= p.file_field :url_path, multiple: true, name: "images[url_path][]", class: "upload-image" %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
  <%= f.label :category, "Category" %>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing Admin Product</h1>

<%= render "form", admin_product: @admin_product %>

app/views/admin/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Products</h1>

<%= search_form_for [:admin, @search], class: "form" do |f| %>
  <div class="field">
    <%= f.label :name_cont, t("ransack.search_name") %>
    <%= f.text_field :name_cont, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :price_gteq, t("ransack.price_between") %>
    <%= f.number_field :price_gteq, class: "form-control", min: Settings.one %>
    <%= f.label :price_lteq, t("ransack.and") %>
    <%= f.number_field :price_lteq, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Search", class: "btn btn-primary" %>
  </div>
<% end %>

<%= will_paginate %>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= sort_link @search, :name, t("product_admin.name") %></th>
      <th><%= sort_link @search, :description, t("product_admin.description") %></th>
      <th><%= sort_link @search, :quantity, t("product_admin.quantity") %></th>
      <th><%= sort_link @search, :price, t("product_admin.price") %></th>
      <th><%= sort_link @search, :category, t("product_admin.category") %></th>
      <th><%= t "product_admin.status" %></th>
      <th><%= t "product_admin.image" %></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.quantity %></td>
        <td><%= t("product_price", price: product.price) %></td>
        <td><%= product.name_category %></td>
        <td><%= product.status %></td>
        <td><%= image_tag (get_image product), size: Settings.size_image_cart %></td>
        <td><%= link_to t("admin.edit"), edit_admin_product_path(product) %></td>
        <td><%= link_to t("admin.destroy"), admin_product_path(product.id), method: :delete, data: {confirm: t("admin.confirm_delete")} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Admin Product", new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1><%= t "product_admin.new" %></h1>

<%= render "form", admin_product: @admin_product %>